import { Member, Checkin, getWeekIndex } from "./types";

const now = Date.now();
const daysAgo = (n: number) => new Date(now - n * 24 * 60 * 60 * 1000).toISOString();
// misma referencia temporal que daysAgo(), pero para calcular en qué
// "semana" (ver getWeekIndex) cayó esa fecha
const weekOf = (n: number) => getWeekIndex(new Date(now - n * 24 * 60 * 60 * 1000));

// Socios de ejemplo del "Box Rinconada" — gimnasio ficticio para probar el MVP.
// En cuanto conectes Supabase, esto se sustituye por datos reales.
export const mockMembers: Member[] = [
  {
    id: "m1",
    fullName: "Lucía Ferrer",
    memberCode: "LF01",
    totalSesionesValidas: 42,
    ultimaSesion: daysAgo(0.3),
    sesionesUltimos14Dias: 8,
    sesiones14a28DiasAtras: 7,
    xpTotal: 4200,
    racha: 3,
    currentWeekIndex: weekOf(0.3),
    currentWeekSessions: 4,
    anomaliasGps: 0,
    sessionDaysThisMonth: [],
    cashbackMonthKey: null,
    lastComodinClaim: null,
  },
  {
    id: "m2",
    fullName: "Marcos Villa",
    memberCode: "MV02",
    totalSesionesValidas: 30,
    ultimaSesion: daysAgo(6),
    sesionesUltimos14Dias: 2,
    sesiones14a28DiasAtras: 7,
    xpTotal: 3000,
    racha: 0,
    currentWeekIndex: weekOf(6),
    currentWeekSessions: 2,
    anomaliasGps: 0,
    sessionDaysThisMonth: [],
    cashbackMonthKey: null,
    lastComodinClaim: null,
  },
  {
    id: "m3",
    fullName: "Sara Domínguez",
    memberCode: "SD03",
    totalSesionesValidas: 15,
    ultimaSesion: daysAgo(12),
    sesionesUltimos14Dias: 0,
    sesiones14a28DiasAtras: 5,
    xpTotal: 1500,
    racha: 0,
    currentWeekIndex: weekOf(12),
    currentWeekSessions: 1,
    anomaliasGps: 0,
    sessionDaysThisMonth: [],
    cashbackMonthKey: null,
    lastComodinClaim: null,
  },
  {
    id: "m4",
    fullName: "Iván Rueda",
    memberCode: "IR04",
    totalSesionesValidas: 3,
    ultimaSesion: daysAgo(1),
    sesionesUltimos14Dias: 3,
    sesiones14a28DiasAtras: 0,
    xpTotal: 300,
    racha: 0,
    currentWeekIndex: weekOf(1),
    currentWeekSessions: 3,
    anomaliasGps: 0,
    sessionDaysThisMonth: [],
    cashbackMonthKey: null,
    lastComodinClaim: null,
  },
  {
    id: "m5",
    fullName: "Elena Castro",
    memberCode: "EC05",
    totalSesionesValidas: 60,
    ultimaSesion: daysAgo(0.1),
    sesionesUltimos14Dias: 9,
    sesiones14a28DiasAtras: 8,
    xpTotal: 6000,
    racha: 5,
    currentWeekIndex: weekOf(0.1),
    currentWeekSessions: 5,
    anomaliasGps: 0,
    sessionDaysThisMonth: [],
    cashbackMonthKey: null,
    lastComodinClaim: null,
  },
  {
    id: "m6",
    fullName: "Pablo Ariza",
    memberCode: "PA06",
    totalSesionesValidas: 20,
    ultimaSesion: daysAgo(16),
    sesionesUltimos14Dias: 0,
    sesiones14a28DiasAtras: 3,
    xpTotal: 2000,
    racha: 0,
    currentWeekIndex: weekOf(16),
    currentWeekSessions: 0,
    anomaliasGps: 0,
    sessionDaysThisMonth: [],
    cashbackMonthKey: null,
    lastComodinClaim: null,
  },
  {
    id: "m7",
    fullName: "Noa Jiménez",
    memberCode: "NJ07",
    totalSesionesValidas: 8,
    ultimaSesion: daysAgo(2),
    sesionesUltimos14Dias: 5,
    sesiones14a28DiasAtras: 2,
    xpTotal: 800,
    racha: 1,
    currentWeekIndex: weekOf(2),
    currentWeekSessions: 2,
    anomaliasGps: 0,
    sessionDaysThisMonth: [],
    cashbackMonthKey: null,
    lastComodinClaim: null,
  },
];

export const mockCheckins: Checkin[] = [
  {
    id: "c1",
    memberId: "m1",
    memberName: "Lucía Ferrer",
    startedAt: daysAgo(0.3),
    endedAt: daysAgo(0.28),
    durationMinutes: 52,
    isValid: true,
    xpAwarded: 100,
    flaggedAnomaly: false,
  },
  {
    id: "c2",
    memberId: "m5",
    memberName: "Elena Castro",
    startedAt: daysAgo(0.1),
    endedAt: daysAgo(0.08),
    durationMinutes: 61,
    isValid: true,
    xpAwarded: 120,
    flaggedAnomaly: false,
  },
];

export const GYM_NAME = "Box Rinconada";
// El mismo slug que ya se usa en la URL de fichaje (?gym=box-rinconada) —
// se convierte en el identificador con el que se guarda todo lo que es
// propio de este gimnasio (premios, en el futuro también socios reales).
export const GYM_ID = "box-rinconada";
